ServerConfig:
  RunMode: info
  TargetURL: http://127.0.0.1:8889  
  HttpPort: '8888' 
  ReadTimeout: 0
  WriteTimeout: 0
  LogOut: stdout
MiddlewareLogConfig:
  VisitLogFile: ./log/visit.log
  RecoverLogFile: ./log/recover.log
  SkipPath: []